# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Weiwei Chen
tagline:          'A Jekyll theme'
description:      'Ph.D. student at Institute of Logic and Cognition, Sun Yat-sen University. Guest Ph.D. student at Institute for Logic, Language and Computation, University of Amsterdam.
'
url:              https://staff.fnwi.uva.nl/w.chen/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
